[package]
name = "markium"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.16", features = ["derive"] }
clio = { version = "0.3.5", features = ["clap-parse"] }
markdown = "1.0.0-alpha.20"
maud = "0.26.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
